### PR TITLE
Text Review

### PR DESCRIPTION
**Pull request by Oakchre**
Minor corrections to spelling and grammar.

### CODE REVIEW

**Review by Krarilotus — CHANGES_REQUESTED** [review]
prioritize vs prioritise is an American vs British english difference.
-> Do we have consistency for American english on the whole website? I think that american english might be the one that more people are familiar with, so i would stick with that.
-> Same for defense, defense is the american version so i would keep it!
-> Same for behavior and behavioral both are correct american english
-> Hopfarm is a germanized word, i think generally we should go for wording as its in the game, hence here it should be corrected to Hops Farm
-> after its village has been completed, should be singular. Each AI has only one village
-> Customizing again American english
-> Same with color being American vs colour being British
-> armory again American
-> localized is American
-> customize as well

The texts regarding the codebase need some upgrades i guess and for the UCP Options we have a lot of reworked texts, maybe we can pull that from the repository directly, would make life easier to only edit them once. As we also need to get all the translations sorted again as well.

**Review by gynt — APPROVED** [review]

**Comment by gynt** [comment]
@Krarilotus , what are the action points for @Oakchre ? GitHub features a tool to indicate exactly on which line an issue is occurring so the issues can be solved rapidly by the PR creator! Maybe use that!

**Comment by Krarilotus** [comment]
> @Krarilotus , what are the action points for @Oakchre ? GitHub features a tool to indicate exactly on which line an issue is occurring so the issues can be solved rapidly by the PR creator! Maybe use that!

oh wow really? I didn't know. I ll use that next time!

**Comment by gynt** [comment]
@Krarilotus I am also still learning as I go (:

**Review by Oakchre — COMMENTED** [review]
Updated in new PR

**Pull request merged**
